### ISSUE TITLE
dark theme by default

### ISSUE THREAD

**Issue by FlaredCanvas** [qmaster0803/tilingDistro#1]
i dont have free retina supply for every new app i open so please do smth about it

**Comment by qmaster0803** [comment]
Pls provide application names to test on

**Comment by FlaredCanvas** [comment]
nemo, htop, libreoffice

**Comment by qmaster0803** [comment]
I've decided to leave theming to end users, but now there's a configuration section in the wiki, so it's a copy-paste difficulty task to update theme now. Speaking about software like nemo, seems like it's Adwaita theme compatibility issue, try to apply "Yaru-dark" as default theme.
